name: MCP Tool Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-mcp-tests:
    name: Run MCP Tool Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      
      - name: Clone MCP Server Repository
        run: |
          git clone https://github.com/awslabs/dataprocessing-mcp-server.git mcp_server
          cd mcp_server
          pip install -e .
          cd ..
      
      - name: Run MCP Tool tests
        run: |
          python run_tests.py
        env:
          AWS_PROFILE: default # Use the default profile as we're using configured credentials
          AWS_SDK_LOAD_CONFIG: 1
          MCP_SERVER_PATH: ./mcp_server/awslabs/dataprocessing_mcp_server
          AWS_REGION: us-west-1
          TEST_CASES_PATH: tests/glue/test_cases.json
