name: MCP Tool Tests

on:
  push:
    branches:
      - main
      - integration-test-feature
  pull_request:
    branches:
      - main

jobs:
  run-mcp-tests:
    name: Run MCP Tool Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd src/aws-dataprocessing-mcp-server/IntegrationTest
          pip install -r requirements.txt

      - name: Configure AWS credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "region=${{ secrets.AWS_REGION }}" >> ~/.aws/config
          # Create the kathryncoding profile that's hardcoded in run_tests.py
          echo "[kathryncoding]" >> ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[profile kathryncoding]" >> ~/.aws/config
          echo "region=${{ secrets.AWS_REGION }}" >> ~/.aws/config
          # Verify the config was created correctly
          AWS_CONFIG_FILE=~/.aws/config aws configure list

      - name: Modify server path in run_tests.py
        run: |
          cd src/aws-dataprocessing-mcp-server/IntegrationTest
          # Update the hardcoded server path in run_tests.py to match our environment
          sed -i 's|/home/lfqing/workplace/mcp/src/dataprocessing-mcp-server/awslabs/dataprocessing_mcp_server|../awslabs/aws_dataprocessing_mcp_server|g' run_tests.py

      - name: Run MCP Tool tests
        run: |
          cd src/aws-dataprocessing-mcp-server/IntegrationTest
          # Add the current directory to Python path so it can find modules
          PYTHONPATH=$PYTHONPATH:$(pwd) python run_tests.py
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SDK_LOAD_CONFIG: 1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MCP_SERVER_PATH: ../awslabs/aws_dataprocessing_mcp_server
          TEST_CASES_PATH: tests/glue/test_cases.json
