name: MCP Tool Tests

on:
  push:
    branches:
      - main
      - integration-test-feature
  pull_request:
    branches:
      - main

jobs:
  run-mcp-tests:
    name: Run MCP Tool Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd src/aws-dataprocessing-mcp-server/IntegrationTest
          pip install -r requirements.txt

      - name: Run MCP Tool tests
        run: |
          cd src/aws-dataprocessing-mcp-server/IntegrationTest
          # Add the current directory to Python path so it can find modules
          PYTHONPATH=$PYTHONPATH:$(pwd) python run_tests.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-1
          AWS_SDK_LOAD_CONFIG: 1
          MCP_SERVER_PATH: ../awslabs/aws_dataprocessing_mcp_server
          TEST_CASES_PATH: tests/glue/test_cases.json
